[package]
name = "roblib-ctrl-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
roblib-client = { version = "0.1.0", features = ["roland"] }
serialport = "4.2.2"
